import createClient from "openapi-fetch";
import type { paths } from "./api.schema.d.ts"; // generated by openapi-typescript

// leave baseUrl empty to automatically append to the current origin
const client = createClient<paths>({
  // baseUrl: "http://localhost:8000",
});

export class TimeplayedAPI {
  static getClient() {
    return client;
  }

  static async getUser(userId: string) {
    const { data, error } = await this.getClient().GET("/api/user/{userId}", {
      params: {
        path: {
          userId,
        },
        query: {},
      },
    });
    if (error) {
      console.error("Error fetching user:", error);
      throw error;
    }
    return data;
  }

  static async getActivities(
    queryParams: paths["/api/activities"]["get"]["parameters"]["query"],
  ) {
    const { data, error } = await this.getClient().GET("/api/activities", {
      params: {
        query: queryParams,
      },
    });
    if (error) {
      console.error("Error fetching activities:", error);
      throw error;
    }
    return data;
  }

  static async getUsers(
    queryParams: paths["/api/users"]["get"]["parameters"]["query"],
  ) {
    const { data, error } = await this.getClient().GET("/api/users", {
      params: {
        query: queryParams,
      },
    });
    if (error) {
      console.error("Error fetching users:", error);
      throw error;
    }
    return data;
  }

  static async getGames(
    queryParams: paths["/api/games"]["get"]["parameters"]["query"],
  ) {
    const { data, error } = await this.getClient().GET("/api/games", {
      params: {
        query: queryParams,
      },
    });
    if (error) {
      console.error("Error fetching games:", error);
      throw error;
    }
    return data;
  }
}
