/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Users
         * @description Get summarized users. Can also filter by gameId and platformId, and set a before/after timestamp to get a range.
         */
        get: operations["get_users_api_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User */
        get: operations["get_user_api_user__userId__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Activities */
        get: operations["get_activities_api_activities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activities/{activity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Activity */
        get: operations["get_activity_api_activities__activity_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Games */
        get: operations["get_games_api_games_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/game/{gameId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Game */
        get: operations["get_game_api_game__gameId__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/platforms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Platforms */
        get: operations["get_platforms_api_platforms_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/platform/{platformId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Platform */
        get: operations["get_platform_api_platform__platformId__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/totals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Totals */
        get: operations["get_totals_api_totals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/chart/playtime_by_day": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Playtime By Day */
        get: operations["get_playtime_by_day_api_stats_chart_playtime_by_day_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sgdb/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Sgdb
         * @description Searches SteamGridDB for games
         */
        get: operations["search_sgdb_api_sgdb_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sgdb/grids/{sgdb_game_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sgdb Grids
         * @description Gets grids for a game from SteamGridDB
         */
        get: operations["sgdb_grids_api_sgdb_grids__sgdb_game_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sgdb/grids/{sgdb_game_id}/best": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Best Grid Sgdb
         * @description Tries to get the best grid for a game from SteamGridDB
         */
        get: operations["best_grid_sgdb_api_sgdb_grids__sgdb_game_id__best_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/discord/{discord_user_id}/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Discord Avatar */
        get: operations["get_discord_avatar_api_discord__discord_user_id__avatar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** GameWithStats */
        GameWithStats: {
            totals: components["schemas"]["Totals"];
            oldest_activity: components["schemas"]["PublicActivityModel"] | null;
            newest_activity: components["schemas"]["PublicActivityModel"] | null;
            /**
             * Percent
             * @description Share of total playtime
             */
            percent: number;
            game: components["schemas"]["PublicGameModel"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PaginatedActivities */
        PaginatedActivities: {
            /**
             * Total
             * @description Total number of items
             */
            total: number;
            /**
             * Offset
             * @description Offset for pagination
             */
            offset: number;
            /**
             * Limit
             * @description Limit for pagination
             */
            limit: number;
            /** Data */
            data: components["schemas"]["PublicActivityModel"][];
            /**
             * Order
             * @enum {string}
             */
            order: "desc" | "asc";
        };
        /** PaginatedGameWithStats */
        PaginatedGameWithStats: {
            /**
             * Total
             * @description Total number of items
             */
            total: number;
            /**
             * Offset
             * @description Offset for pagination
             */
            offset: number;
            /**
             * Limit
             * @description Limit for pagination
             */
            limit: number;
            /** Data */
            data: components["schemas"]["GameWithStats"][];
        };
        /** PaginatedPlatformsWithStats */
        PaginatedPlatformsWithStats: {
            /**
             * Total
             * @description Total number of items
             */
            total: number;
            /**
             * Offset
             * @description Offset for pagination
             */
            offset: number;
            /**
             * Limit
             * @description Limit for pagination
             */
            limit: number;
            /** Data */
            data: components["schemas"]["PlatformWithStats"][];
        };
        /** PaginatedUserWithStats */
        PaginatedUserWithStats: {
            /**
             * Total
             * @description Total number of items
             */
            total: number;
            /**
             * Offset
             * @description Offset for pagination
             */
            offset: number;
            /**
             * Limit
             * @description Limit for pagination
             */
            limit: number;
            /** Data */
            data: components["schemas"]["UserWithStats"][];
        };
        /** PlatformWithStats */
        PlatformWithStats: {
            totals: components["schemas"]["Totals"];
            oldest_activity: components["schemas"]["PublicActivityModel"] | null;
            newest_activity: components["schemas"]["PublicActivityModel"] | null;
            /**
             * Percent
             * @description Share of total playtime
             */
            percent: number;
            platform: components["schemas"]["PublicPlatformModel"];
        };
        /** PublicActivityModel */
        PublicActivityModel: {
            /**
             * Id
             * @description ID for the activity
             */
            id: number;
            /**
             * Timestamp
             * @description Timestamp for the activity
             */
            timestamp: number;
            /**
             * Seconds
             * @description Duration of the activity in seconds
             */
            seconds: number;
            /** @description User associated with the activity */
            user: components["schemas"]["PublicUserModel"];
            /** @description Game associated with the activity */
            game: components["schemas"]["PublicGameModel"];
            /** @description Platform associated with the activity */
            platform: components["schemas"]["PublicPlatformModel"];
        };
        /** PublicGameModel */
        PublicGameModel: {
            /**
             * Id
             * @description ID for the game
             */
            id: number;
            /**
             * Name
             * @description Name of the game
             */
            name: string;
            /**
             * Steam Id
             * @description Steam ID for the game
             */
            steam_id: number | null;
            /**
             * Sgdb Id
             * @description SGDB ID for the game
             */
            sgdb_id: number | null;
            /**
             * Image Url
             * @description Image URL for the game
             */
            image_url: string | null;
            /**
             * Aliases
             * @description List of aliases for the game
             */
            aliases: string[];
            /**
             * Release Year
             * @description Release year of the game
             */
            release_year: number | null;
        };
        /** PublicPlatformModel */
        PublicPlatformModel: {
            /**
             * Id
             * @description ID for the platform
             */
            id: number;
            /**
             * Abbreviation
             * @description Abbreviation for the platform
             */
            abbreviation: string;
            /**
             * Name
             * @description Name of the platform
             */
            name: string | null;
        };
        /** PublicUserModel */
        PublicUserModel: {
            /**
             * Id
             * @description Discord ID for the user
             */
            id: string;
            /**
             * Name
             * @description Name of the user
             */
            name: string;
            /** @description User's default platform */
            default_platform: components["schemas"]["PublicPlatformModel"];
        };
        /** SGDB_Author */
        SGDB_Author: {
            /** Name */
            name: string | null;
            /** Steam64 */
            steam64: string | null;
            /** Avatar */
            avatar: string | null;
        };
        /** SGDB_Game */
        SGDB_Game: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Verified */
            verified: boolean;
            /** Release Date */
            release_date: number;
        };
        /** SGDB_Grid */
        SGDB_Grid: {
            /** Id */
            id: number | null;
            /** Score */
            score: number | null;
            /** Width */
            width: number | null;
            /** Height */
            height: number | null;
            /** Style */
            style: string | null;
            /** Mime */
            mime: string | null;
            /** Language */
            language: string | null;
            /** Url */
            url: string | null;
            /** Thumb */
            thumb: string | null;
            /** Type */
            type: string | null;
            author: components["schemas"]["SGDB_Author"] | null;
            /** Upvotes */
            upvotes: number | null;
            /** Downvotes */
            downvotes: number | null;
        };
        /** Totals */
        Totals: {
            /**
             * Playtime Secs
             * @description Total playtime in seconds
             */
            playtime_secs: number;
            /**
             * Activity Count
             * @description Total number of activities
             */
            activity_count: number;
            /**
             * User Count
             * @description Total number of unique users
             */
            user_count: number;
            /**
             * Game Count
             * @description Total number of unique games
             */
            game_count: number;
            /**
             * Platform Count
             * @description Total number of unique platforms
             */
            platform_count: number;
        };
        /** UserWithStats */
        UserWithStats: {
            user: components["schemas"]["PublicUserModel"];
            oldest_activity: components["schemas"]["PublicActivityModel"];
            newest_activity: components["schemas"]["PublicActivityModel"];
            totals: components["schemas"]["Totals"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_users_api_users_get: {
        parameters: {
            query?: {
                offset?: unknown;
                limit?: unknown;
                gameId?: number | null;
                platformId?: number | null;
                before?: number | null;
                after?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedUserWithStats"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_api_user__userId__get: {
        parameters: {
            query?: {
                before?: number | null;
                after?: number | null;
                gameId?: number | null;
                platformId?: number | null;
            };
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserWithStats"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_activities_api_activities_get: {
        parameters: {
            query?: {
                offset?: unknown;
                limit?: unknown;
                order?: "desc" | "asc";
                user?: string | null;
                game?: number | null;
                platform?: number | null;
                before?: number | null;
                after?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedActivities"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_activity_api_activities__activity_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                activity_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicActivityModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_games_api_games_get: {
        parameters: {
            query?: {
                offset?: unknown;
                limit?: unknown;
                userId?: string | null;
                platformId?: number | null;
                before?: number | null;
                after?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedGameWithStats"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_game_api_game__gameId__get: {
        parameters: {
            query?: {
                userId?: string | null;
                before?: number | null;
                after?: number | null;
                platformId?: number | null;
            };
            header?: never;
            path: {
                gameId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameWithStats"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_platforms_api_platforms_get: {
        parameters: {
            query?: {
                offset?: unknown;
                limit?: unknown;
                userId?: string | null;
                gameId?: number | null;
                before?: number | null;
                after?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPlatformsWithStats"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_platform_api_platform__platformId__get: {
        parameters: {
            query?: {
                userId?: string | null;
                before?: number | null;
                after?: number | null;
                gameId?: number | null;
            };
            header?: never;
            path: {
                platformId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformWithStats"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_totals_api_totals_get: {
        parameters: {
            query?: {
                userId?: string | null;
                gameId?: number | null;
                platformId?: number | null;
                before?: number | null;
                after?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Totals"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_playtime_by_day_api_stats_chart_playtime_by_day_get: {
        parameters: {
            query?: {
                userId?: string | null;
                gameId?: number | null;
                platformId?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_sgdb_api_sgdb_search_get: {
        parameters: {
            query: {
                query: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SGDB_Game"][] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sgdb_grids_api_sgdb_grids__sgdb_game_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sgdb_game_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SGDB_Grid"][] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    best_grid_sgdb_api_sgdb_grids__sgdb_game_id__best_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sgdb_game_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SGDB_Grid"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_discord_avatar_api_discord__discord_user_id__avatar_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                discord_user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
