/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ping */
        get: operations["ping_ping_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Info */
        get: operations["info_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user-stats/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Single User Stats */
        get: operations["get_single_user_stats_user_stats__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users-stats/{user_ids}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Many Users Stats */
        get: operations["get_many_users_stats_users_stats__user_ids__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users-stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Users Stats */
        get: operations["get_users_stats_users_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Single User */
        get: operations["get_single_user_user__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_ids}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Many Users */
        get: operations["get_many_users_users__user_ids__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Users */
        get: operations["get_users_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/who_am_i": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Who Am I */
        get: operations["who_am_i_who_am_i_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Activity */
        post: operations["add_activity_activity_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/activity/newest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Newest Activity */
        get: operations["get_newest_activity_activity_newest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/activity/oldest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Oldest Activity */
        get: operations["get_oldest_activity_activity_oldest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/activity/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Live Activity */
        get: operations["get_live_activity_activity_live_get"];
        put?: never;
        /** Start Live Activity */
        post: operations["start_live_activity_activity_live_post"];
        /** Abort Live Activity */
        delete: operations["abort_live_activity_activity_live_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/activity/live/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop Live Activity */
        post: operations["stop_live_activity_activity_live_stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/activity/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Single Activity */
        get: operations["get_single_activity_activity__id__get"];
        put?: never;
        post?: never;
        /** Delete Activity */
        delete: operations["delete_activity_activity__id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/activities/{ids}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Many Activities */
        get: operations["get_many_activities_activities__ids__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Activities */
        get: operations["get_activities_activities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/total": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Total */
        get: operations["get_total_total_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/game-stats/{game_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Single Game Stats */
        get: operations["get_single_game_stats_game_stats__game_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games-stats/{game_ids}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Many Games Stats */
        get: operations["get_many_games_stats_games_stats__game_ids__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games-stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Games Stats */
        get: operations["get_games_stats_games_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/game/{game_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Single Game */
        get: operations["get_single_game_game__game_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/game_igdb/{igdb_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Single Game By Igdb Id
         * @description Get a game by its IGDB ID. If the game is not in the database, it will be created from IGDB data.
         */
        get: operations["get_single_game_by_igdb_id_game_igdb__igdb_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_ids}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Many Games */
        get: operations["get_many_games_games__game_ids__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Games */
        get: operations["get_games_games_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/platform-stats/{platform_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Single Platform Stats */
        get: operations["get_single_platform_stats_platform_stats__platform_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/platforms-stats/{platform_ids}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Many Platforms Stats */
        get: operations["get_many_platforms_stats_platforms_stats__platform_ids__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/platforms-stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Platforms Stats */
        get: operations["get_platforms_stats_platforms_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/platform/{platform_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Single Platform */
        get: operations["get_single_platform_platform__platform_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/platforms/{platform_ids}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Many Platforms */
        get: operations["get_many_platforms_platforms__platform_ids__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/platforms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Platforms */
        get: operations["get_platforms_platforms_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/charts/playtime/by_day": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Playtime By Day */
        get: operations["get_playtime_by_day_charts_playtime_by_day_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/discord/{discord_user_id}/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Redirect Discord Avatar
         * @description Redirects to URL for Discord avatar
         */
        get: operations["redirect_discord_avatar_discord__discord_user_id__avatar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sgdb/{sgdb_game_id}/grids/best": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Best Grid Sgdb
         * @description Tries to get the best grid for a game from SteamGridDB
         */
        get: operations["best_grid_sgdb_sgdb__sgdb_game_id__grids_best_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sgdb/{sgdb_game_id}/grids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sgdb Grids
         * @description Gets grids for a game from SteamGridDB
         */
        get: operations["sgdb_grids_sgdb__sgdb_game_id__grids_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sgdb/{sgdb_game_id}/grids/{grid_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sgdb Grid By Id
         * @description Gets a grid by ID for a game from SteamGridDB
         */
        get: operations["sgdb_grid_by_id_sgdb__sgdb_game_id__grids__grid_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/igdb/game/{igdb_game_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Igdb Game Info
         * @description Get game info from IGDB by their ID
         */
        get: operations["get_igdb_game_info_igdb_game__igdb_game_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** API_Activity */
        API_Activity: {
            /** Id */
            id: number;
            /**
             * Started
             * @description Timestamp of when the activity started in milliseconds since epoch
             */
            started: number;
            /**
             * Ended
             * @description Timestamp of when the activity ended in milliseconds since epoch
             */
            ended: number;
            /**
             * Timestamp
             * @deprecated
             * @description Same as ended, kept for backwards compatibility
             */
            timestamp: number;
            /** Seconds */
            seconds: number;
            /** User Id */
            user_id: number;
            /** Game Id */
            game_id: number;
            /** Platform Id */
            platform_id: number;
            /** Created */
            created: number;
            /** Updated */
            updated: number;
        };
        /** API_Game */
        API_Game: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Sgdb Id */
            sgdb_id: number | null;
            /** Sgdb Grid Id */
            sgdb_grid_id: number | null;
            /** Igdb Id */
            igdb_id: number | null;
            /** Steam Id */
            steam_id: number | null;
            /** Image Url */
            image_url: string | null;
            /** Aliases */
            aliases: string[];
            /** Release Year */
            release_year: number | null;
            /** Created */
            created: number;
            /** Updated */
            updated: number;
            /** Children Ids */
            children_ids: number[];
            /** Parent Id */
            parent_id: number | null;
        };
        /** API_GameWithStats */
        API_GameWithStats: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Sgdb Id */
            sgdb_id: number | null;
            /** Sgdb Grid Id */
            sgdb_grid_id: number | null;
            /** Igdb Id */
            igdb_id: number | null;
            /** Steam Id */
            steam_id: number | null;
            /** Image Url */
            image_url: string | null;
            /** Aliases */
            aliases: string[];
            /** Release Year */
            release_year: number | null;
            /** Created */
            created: number;
            /** Updated */
            updated: number;
            /** Children Ids */
            children_ids: number[];
            /** Parent Id */
            parent_id: number | null;
            stats: components["schemas"]["GameStats"];
        };
        /** API_LiveActivity */
        API_LiveActivity: {
            /** Id */
            id: number;
            /**
             * Started
             * @description Timestamp of when the activity started in milliseconds since epoch
             */
            started: number;
            /** User Id */
            user_id: number;
            /** Game Id */
            game_id: number;
            /** Platform Id */
            platform_id: number;
        };
        /** API_Platform */
        API_Platform: {
            /** Id */
            id: number;
            /** Display Name */
            display_name: string;
            /** Abbreviation */
            abbreviation: string;
            /** Name */
            name: string | null;
            /** Color Primary */
            color_primary: string | null;
            /** Color Secondary */
            color_secondary: string | null;
            /** Icon */
            icon: string | null;
            /** Created */
            created: number;
            /** Updated */
            updated: number;
        };
        /** API_PlatformWithStats */
        API_PlatformWithStats: {
            /** Id */
            id: number;
            /** Display Name */
            display_name: string;
            /** Abbreviation */
            abbreviation: string;
            /** Name */
            name: string | null;
            /** Color Primary */
            color_primary: string | null;
            /** Color Secondary */
            color_secondary: string | null;
            /** Icon */
            icon: string | null;
            /** Created */
            created: number;
            /** Updated */
            updated: number;
            stats: components["schemas"]["PlatformTotals"];
        };
        /** API_PostActivity */
        API_PostActivity: {
            /**
             * Seconds
             * @description Length of the activity in seconds
             */
            seconds: number;
            /**
             * Game Id
             * @description Timeplayed ID of the game being played, can be null if igdb or steam id is provided
             */
            game_id?: number | null;
            /**
             * Igdb Id
             * @description IGDB ID of the game being played, can be null if game or steam id is provided
             */
            igdb_id?: number | null;
            /**
             * Steam Id
             * @description Steam App ID of the game being played, can be null if game or igdb id is provided
             */
            steam_id?: number | null;
            /**
             * Platform Id
             * @description ID of platform that was played on. Will default to user's default platform if not provided
             */
            platform_id?: number | null;
        };
        /** API_PostLiveActivity */
        API_PostLiveActivity: {
            /**
             * Game Id
             * @description ID of the game being played, can be null if igdb_id is provided
             */
            game_id?: number | null;
            /**
             * Igdb Id
             * @description IGDB ID of the game being played, can be null if game_id is provided
             */
            igdb_id?: number | null;
            /**
             * Platform Id
             * @description ID of platform that was played on. Will default to user's default platform if not provided
             */
            platform_id?: number | null;
        };
        /** API_User */
        API_User: {
            /** Id */
            id: number;
            /** Discord Id */
            discord_id: string | null;
            /**
             * Name
             * @default Discord username typically
             */
            name: string;
            /**
             * Display Name
             * @default Discord display name
             */
            display_name: string;
            /** Default Platform Id */
            default_platform_id: number;
            /** Created */
            created: number;
            /** Updated */
            updated: number;
        };
        /** API_UserWithStats */
        API_UserWithStats: {
            /** Id */
            id: number;
            /** Discord Id */
            discord_id: string | null;
            /**
             * Name
             * @default Discord username typically
             */
            name: string;
            /**
             * Display Name
             * @default Discord display name
             */
            display_name: string;
            /** Default Platform Id */
            default_platform_id: number;
            /** Created */
            created: number;
            /** Updated */
            updated: number;
            stats: components["schemas"]["UserTotals"];
        };
        /** Data */
        Data: {
            /** Label */
            label: string;
            /** Data */
            data: number[];
        };
        /** GameStats */
        GameStats: {
            /**
             * Seconds
             * @description Total playtime in seconds
             */
            seconds: number;
            /**
             * Activity Count
             * @description Total number of activities
             */
            activity_count: number;
            /**
             * First Activity
             * @description Timestamp of the first activity
             */
            first_activity: number | null;
            /**
             * Last Activity
             * @description Timestamp of the last activity
             */
            last_activity: number | null;
            /** User Count */
            user_count: number;
            /** Platform Count */
            platform_count: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IGDB_Cover */
        IGDB_Cover: {
            /** Id */
            id: number;
            /** Image Id */
            image_id: string;
        };
        /** IGDB_GameInfo */
        IGDB_GameInfo: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** First Release Date */
            first_release_date?: number | null;
            /** Url */
            url: string;
            /** Summary */
            summary?: string | null;
            cover?: components["schemas"]["IGDB_Cover"] | null;
            /** Platforms */
            platforms?: number[] | null;
            /** Involved Companies */
            involved_companies?: number[] | null;
            /**
             * Similar Games
             * @default []
             */
            similar_games: number[];
            /**
             * Expanded Games
             * @default []
             */
            expanded_games: number[];
            /**
             * Expansions
             * @default []
             */
            expansions: number[];
            /** Parent Game */
            parent_game?: number | null;
            /**
             * Ports
             * @default []
             */
            ports: number[];
            /**
             * Remakes
             * @default []
             */
            remakes: number[];
            /**
             * Remasters
             * @default []
             */
            remasters: number[];
            /**
             * Standalone Expansions
             * @default []
             */
            standalone_expansions: number[];
        };
        /** Info */
        Info: {
            /** Version */
            version: string;
            /** Uptime */
            uptime: number;
        };
        /** PlatformTotals */
        PlatformTotals: {
            /**
             * Seconds
             * @description Total playtime in seconds
             */
            seconds: number;
            /**
             * Activity Count
             * @description Total number of activities
             */
            activity_count: number;
            /**
             * First Activity
             * @description Timestamp of the first activity
             */
            first_activity: number | null;
            /**
             * Last Activity
             * @description Timestamp of the last activity
             */
            last_activity: number | null;
            /** User Count */
            user_count: number;
            /** Game Count */
            game_count: number;
        };
        /** PlaytimeChart */
        PlaytimeChart: {
            /** Labels */
            labels: string[];
            /** Datasets */
            datasets: components["schemas"]["Data"][];
        };
        /** SGDB_Author */
        SGDB_Author: {
            /** Name */
            name: string | null;
            /** Steam64 */
            steam64: string | null;
            /** Avatar */
            avatar: string | null;
        };
        /** SGDB_Grid */
        SGDB_Grid: {
            /** Id */
            id: number | null;
            /** Score */
            score: number | null;
            /** Width */
            width: number | null;
            /** Height */
            height: number | null;
            /** Style */
            style: string | null;
            /** Mime */
            mime: string | null;
            /** Language */
            language: string | null;
            /** Url */
            url: string | null;
            /** Thumb */
            thumb: string | null;
            /** Type */
            type: string | null;
            author: components["schemas"]["SGDB_Author"] | null;
            /** Upvotes */
            upvotes: number | null;
            /** Downvotes */
            downvotes: number | null;
        };
        /** Total */
        Total: {
            /**
             * Seconds
             * @description Total playtime in seconds
             */
            seconds: number;
            /**
             * Activity Count
             * @description Total number of activities
             */
            activity_count: number;
            /**
             * First Activity
             * @description Timestamp of the first activity
             */
            first_activity: number | null;
            /**
             * Last Activity
             * @description Timestamp of the last activity
             */
            last_activity: number | null;
            /** User Count */
            user_count: number;
            /** Platform Count */
            platform_count: number;
            /** Game Count */
            game_count: number;
        };
        /** UserTotals */
        UserTotals: {
            /**
             * Seconds
             * @description Total playtime in seconds
             */
            seconds: number;
            /**
             * Activity Count
             * @description Total number of activities
             */
            activity_count: number;
            /**
             * First Activity
             * @description Timestamp of the first activity
             */
            first_activity: number | null;
            /**
             * Last Activity
             * @description Timestamp of the last activity
             */
            last_activity: number | null;
            /**
             * Game Count
             * @description Total number of unique games
             */
            game_count: number;
            /**
             * Platform Count
             * @description Total number of unique platforms
             */
            platform_count: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ping_ping_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    info_info_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Info"];
                };
            };
        };
    };
    get_single_user_stats_user_stats__user_id__get: {
        parameters: {
            query?: {
                /** @description Timestamp (in milliseconds). Only include activities before this timestamp. */
                before?: number;
                /** @description Timestamp (in milliseconds). Only include activities after this timestamp. */
                after?: number;
                game?: number | null;
                platform?: number | null;
            };
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["API_UserWithStats"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_many_users_stats_users_stats__user_ids__get: {
        parameters: {
            query?: {
                /** @description Timestamp (in milliseconds). Only include activities before this timestamp. */
                before?: number;
                /** @description Timestamp (in milliseconds). Only include activities after this timestamp. */
                after?: number;
                /** @description ID of the game to filter by */
                game?: number;
                /** @description ID of the platform to filter by */
                platform?: number;
                /** @description Sort by */
                sort?: "playtime" | "activity_count" | "last_activity" | "first_activity" | "game_count" | "platform_count" | "name" | "id";
                order?: "asc" | "desc";
            };
            header?: never;
            path: {
                /** @description Comma-separated list of user ids to filter by */
                user_ids: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["API_UserWithStats"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_users_stats_users_stats_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
                /** @description ID of the game to filter by */
                game?: number;
                /** @description ID of the platform to filter by */
                platform?: number;
                /** @description Timestamp (in milliseconds). Only include activities before this timestamp. */
                before?: number;
                /** @description Timestamp (in milliseconds). Only include activities after this timestamp. */
                after?: number;
                /** @description Sort by */
                sort?: "playtime" | "activity_count" | "last_activity" | "first_activity" | "game_count" | "platform_count" | "name" | "id";
                order?: "asc" | "desc";
                /** @description Search term to filter users by */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["API_UserWithStats"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_single_user_user__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["API_User"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_many_users_users__user_ids__get: {
        parameters: {
            query?: {
                /** @description Sort by */
                sort?: "name" | "id" | "created" | "updated";
                order?: "asc" | "desc";
            };
            header?: never;
            path: {
                /** @description Comma-separated list of user ids to filter by */
                user_ids: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["API_User"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_users_users_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
                /** @description Sort by */
                sort?: "name" | "id" | "created" | "updated";
                order?: "asc" | "desc";
                /** @description Search term to filter users by */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["API_User"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    who_am_i_who_am_i_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["API_User"];
                };
            };
        };
    };
    add_activity_activity_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["API_PostActivity"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["API_Activity"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_newest_activity_activity_newest_get: {
        parameters: {
            query?: {
                /** @description ID of the user to filter by */
                user?: number;
                /** @description ID of the game to filter by */
                game?: number;
                /** @description ID of the platform to filter by */
                platform?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["API_Activity"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_oldest_activity_activity_oldest_get: {
        parameters: {
            query?: {
                /** @description ID of the user to filter by */
                user?: number;
                /** @description ID of the game to filter by */
                game?: number;
                /** @description ID of the platform to filter by */
                platform?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["API_Activity"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_live_activity_activity_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["API_LiveActivity"];
                };
            };
        };
    };
    start_live_activity_activity_live_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["API_PostLiveActivity"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["API_LiveActivity"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    abort_live_activity_activity_live_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    stop_live_activity_activity_live_stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["API_Activity"];
                };
            };
        };
    };
    get_single_activity_activity__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["API_Activity"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_activity_activity__id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_many_activities_activities__ids__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Comma-separated list of activity ids to filter by */
                ids: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["API_Activity"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_activities_activities_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
                order?: "asc" | "desc";
                /** @description Sort by */
                sort?: "id" | "timestamp";
                /** @description ID of the user to filter by */
                user?: number;
                /** @description ID of the game to filter by */
                game?: number;
                /** @description ID of the platform to filter by */
                platform?: number;
                /** @description Timestamp (in milliseconds). Only include activities before this timestamp. */
                before?: number;
                /** @description Timestamp (in milliseconds). Only include activities after this timestamp. */
                after?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["API_Activity"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_total_total_get: {
        parameters: {
            query?: {
                /** @description Comma-separated list of users to filter by */
                users?: string;
                /** @description Comma-separated list of games to filter by */
                games?: string;
                /** @description Comma-separated list of platforms to filter by */
                platforms?: string;
                /** @description Timestamp (in milliseconds). Only include activities before this timestamp. */
                before?: number;
                /** @description Timestamp (in milliseconds). Only include activities after this timestamp. */
                after?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Total"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_single_game_stats_game_stats__game_id__get: {
        parameters: {
            query?: {
                /** @description Timestamp (in milliseconds). Only include activities before this timestamp. */
                before?: number;
                /** @description Timestamp (in milliseconds). Only include activities after this timestamp. */
                after?: number;
                /** @description ID of the user to filter by */
                user?: number;
                /** @description ID of the platform to filter by */
                platform?: number;
            };
            header?: never;
            path: {
                /** @description ID of the game to filter by */
                game_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["API_GameWithStats"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_many_games_stats_games_stats__game_ids__get: {
        parameters: {
            query?: {
                /** @description Timestamp (in milliseconds). Only include activities before this timestamp. */
                before?: number;
                /** @description Timestamp (in milliseconds). Only include activities after this timestamp. */
                after?: number;
                /** @description ID of the user to filter by */
                user?: number;
                /** @description ID of the platform to filter by */
                platform?: number;
                /** @description Sort by */
                sort?: "playtime" | "activity_count" | "last_activity" | "first_activity" | "user_count" | "platform_count" | "name" | "id";
                order?: "asc" | "desc";
            };
            header?: never;
            path: {
                /** @description Comma-separated list of game ids to filter by */
                game_ids: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["API_GameWithStats"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_games_stats_games_stats_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
                /** @description ID of the user to filter by */
                user?: number;
                /** @description ID of the platform to filter by */
                platform?: number;
                /** @description Timestamp (in milliseconds). Only include activities before this timestamp. */
                before?: number;
                /** @description Timestamp (in milliseconds). Only include activities after this timestamp. */
                after?: number;
                /** @description Sort by */
                sort?: "playtime" | "activity_count" | "last_activity" | "first_activity" | "user_count" | "platform_count" | "name" | "id";
                order?: "asc" | "desc";
                /** @description Search term to filter games by */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["API_GameWithStats"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_single_game_game__game_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of the game to filter by */
                game_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["API_Game"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_single_game_by_igdb_id_game_igdb__igdb_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of the IGDB game to filter by */
                igdb_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["API_Game"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_many_games_games__game_ids__get: {
        parameters: {
            query?: {
                /** @description Sort by */
                sort?: "name" | "id" | "created" | "updated" | "release_year";
                order?: "asc" | "desc";
            };
            header?: never;
            path: {
                /** @description Comma-separated list of game ids to filter by */
                game_ids: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["API_Game"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_games_games_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
                /** @description Sort by */
                sort?: "name" | "id" | "created" | "updated" | "release_year";
                order?: "asc" | "desc";
                /** @description Search term to filter games by */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["API_Game"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_single_platform_stats_platform_stats__platform_id__get: {
        parameters: {
            query?: {
                /** @description Timestamp (in milliseconds). Only include activities before this timestamp. */
                before?: number;
                /** @description Timestamp (in milliseconds). Only include activities after this timestamp. */
                after?: number;
                /** @description ID of the user to filter by */
                user?: number;
                /** @description ID of the game to filter by */
                game?: number;
            };
            header?: never;
            path: {
                /** @description ID of the platform to filter by */
                platform_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["API_PlatformWithStats"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_many_platforms_stats_platforms_stats__platform_ids__get: {
        parameters: {
            query?: {
                /** @description Timestamp (in milliseconds). Only include activities before this timestamp. */
                before?: number;
                /** @description Timestamp (in milliseconds). Only include activities after this timestamp. */
                after?: number;
                /** @description ID of the user to filter by */
                user?: number;
                /** @description ID of the game to filter by */
                game?: number;
                /** @description Sort by */
                sort?: "playtime" | "activity_count" | "last_activity" | "first_activity" | "user_count" | "game_count" | "name" | "id";
                order?: "asc" | "desc";
            };
            header?: never;
            path: {
                /** @description Comma-separated list of platform ids to filter by */
                platform_ids: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["API_PlatformWithStats"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_platforms_stats_platforms_stats_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
                /** @description ID of the user to filter by */
                user?: number;
                /** @description ID of the game to filter by */
                game?: number;
                /** @description Timestamp (in milliseconds). Only include activities before this timestamp. */
                before?: number;
                /** @description Timestamp (in milliseconds). Only include activities after this timestamp. */
                after?: number;
                /** @description Sort by */
                sort?: "playtime" | "activity_count" | "last_activity" | "first_activity" | "user_count" | "game_count" | "name" | "id";
                order?: "asc" | "desc";
                /** @description Search term to filter platforms by */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["API_PlatformWithStats"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_single_platform_platform__platform_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                platform_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["API_Platform"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_many_platforms_platforms__platform_ids__get: {
        parameters: {
            query?: {
                /** @description Sort by */
                sort?: "name" | "id" | "created" | "updated";
                order?: "asc" | "desc";
            };
            header?: never;
            path: {
                /** @description Comma-separated list of platform ids to filter by */
                platform_ids: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["API_Platform"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_platforms_platforms_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
                /** @description Sort by */
                sort?: "name" | "id" | "created" | "updated";
                order?: "asc" | "desc";
                /** @description Search term to filter platforms by */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["API_Platform"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_playtime_by_day_charts_playtime_by_day_get: {
        parameters: {
            query?: {
                /** @description ID of the user to filter by */
                user?: number;
                /** @description ID of the game to filter by */
                game?: number;
                /** @description ID of the platform to filter by */
                platform?: number;
                /** @description Timestamp (in milliseconds). Only include activities before this timestamp. */
                before?: number;
                /** @description Timestamp (in milliseconds). Only include activities after this timestamp. */
                after?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaytimeChart"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    redirect_discord_avatar_discord__discord_user_id__avatar_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                discord_user_id: string | number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    best_grid_sgdb_sgdb__sgdb_game_id__grids_best_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sgdb_game_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SGDB_Grid"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sgdb_grids_sgdb__sgdb_game_id__grids_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sgdb_game_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SGDB_Grid"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sgdb_grid_by_id_sgdb__sgdb_game_id__grids__grid_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sgdb_game_id: number;
                grid_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SGDB_Grid"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_igdb_game_info_igdb_game__igdb_game_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                igdb_game_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IGDB_GameInfo"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
