import createClient from "openapi-fetch";
import type { paths } from "./api.schema.d.ts"; // generated by openapi-typescript

const client = createClient<paths>({
  // fetch: _fetch, // can hijack fetch if needed
  // leave baseUrl empty to automatically append to the current origin
  // baseUrl: "http://localhost:8000",
});

function getSessionCache(key: string) {
  const cached = sessionStorage.getItem(key);
  if (cached) {
    //console.log("cache hit", key);
    return JSON.parse(cached);
  }
  return null;
}

function storeSessionCache(key: string, value: any) {
  try {
    sessionStorage.setItem(key, JSON.stringify(value));
  } catch (e) {
    console.error("Error storing session cache:", e);
  }
}

export class TimeplayedAPI {
  static getClient() {
    return client;
  }

  /////////////// USERS //////////////////

  static async getUser(user_id: number) {
    const key = `api_getUser_${user_id}`;
    const cached = getSessionCache(key);
    if (cached) {
      return cached as paths["/api/user/{user_id}"]["get"]["responses"]["200"]["content"]["application/json"];
    }
    const { data, error } = await this.getClient().GET("/api/user/{user_id}", {
      params: {
        path: {
          user_id,
        },
      },
    });
    if (error) {
      console.error("Error fetching user:", error);
      throw error;
    }
    storeSessionCache(key, data);
    return data;
  }

  static async getUsers(
    query: paths["/api/users"]["get"]["parameters"]["query"],
  ) {
    const { data, error } = await this.getClient().GET("/api/users", {
      params: {
        query,
      },
    });
    if (error) {
      console.error("Error fetching users:", error);
      throw error;
    }
    return data;
  }

  static async getUserStats(user_id: number) {
    const { data, error } = await this.getClient().GET(
      "/api/user-stats/{user_id}",
      {
        params: {
          path: {
            user_id,
          },
        },
      },
    );
    if (error) {
      console.error("Error fetching user stats:", error);
      throw error;
    }
    return data;
  }

  static async getUsersStats(
    query: paths["/api/users-stats"]["get"]["parameters"]["query"],
  ) {
    const { data, error } = await this.getClient().GET("/api/users-stats", {
      params: {
        query,
      },
    });
    if (error) {
      console.error("Error fetching users stats:", error);
      throw error;
    }
    return data;
  }

  ///////////////// PLATFORMS ////////////////

  static async getPlatform(platform_id: number) {
    const key = `api_getPlatform_${platform_id}`;
    const cached = getSessionCache(key);
    if (cached) {
      return cached as paths["/api/platform/{platform_id}"]["get"]["responses"]["200"]["content"]["application/json"];
    }
    const { data, error } = await this.getClient().GET(
      "/api/platform/{platform_id}",
      {
        params: {
          path: {
            platform_id,
          },
        },
      },
    );
    if (error) {
      console.error("Error fetching platform:", error);
      throw error;
    }
    storeSessionCache(key, data);
    return data;
  }

  static async getPlatforms(
    query: paths["/api/platforms"]["get"]["parameters"]["query"],
  ) {
    const { data, error } = await this.getClient().GET("/api/platforms", {
      params: {
        query,
      },
    });
    if (error) {
      console.error("Error fetching platforms:", error);
      throw error;
    }
    return data;
  }

  static async getPlatformStats(platform_id: number) {
    const { data, error } = await this.getClient().GET(
      "/api/platform-stats/{platform_id}",
      {
        params: {
          path: {
            platform_id,
          },
        },
      },
    );
    if (error) {
      console.error("Error fetching platform:", error);
      throw error;
    }
    return data;
  }

  static async getPlatformsStats(
    query: paths["/api/platforms-stats"]["get"]["parameters"]["query"],
  ) {
    const { data, error } = await this.getClient().GET("/api/platforms-stats", {
      params: {
        query,
      },
    });
    if (error) {
      console.error("Error fetching games stats:", error);
      throw error;
    }
    return data;
  }

  //////////////// GAMES /////////////

  static async getGame(game_id: number) {
    const key = `api_getGame_${game_id}`;
    const cached = getSessionCache(key);
    if (cached) {
      return cached as paths["/api/game/{game_id}"]["get"]["responses"]["200"]["content"]["application/json"];
    }
    const { data, error } = await this.getClient().GET("/api/game/{game_id}", {
      params: {
        path: {
          game_id,
        },
      },
    });
    if (error) {
      console.error("Error fetching game:", error);
      throw error;
    }
    storeSessionCache(key, data);
    return data;
  }

  static async getGames(
    query: paths["/api/games"]["get"]["parameters"]["query"],
  ) {
    const { data, error } = await this.getClient().GET("/api/games", {
      params: {
        query,
      },
    });
    if (error) {
      console.error("Error fetching games:", error);
      throw error;
    }
    return data;
  }

  static async getGameStats(game_id: number) {
    const { data, error } = await this.getClient().GET(
      "/api/game-stats/{game_id}",
      {
        params: {
          path: {
            game_id,
          },
        },
      },
    );
    if (error) {
      console.error("Error fetching game stats:", error);
      throw error;
    }
    return data;
  }

  static async getGameStatsMany(game_ids: number[]) {
    //console.log("Executing with", game_ids, game_ids.join(","));
    const { data, error } = await this.getClient().GET(
      "/api/games-stats/{game_ids}",
      {
        params: {
          path: {
            game_ids: game_ids.join(","),
          },
        },
      },
    );

    if (error) {
      console.error("Error fetching game stats:", error);
      throw error;
    }
    return data;
  }

  static async getGamesStats(
    query: paths["/api/games-stats"]["get"]["parameters"]["query"],
  ) {
    const { data, error } = await this.getClient().GET("/api/games-stats", {
      params: {
        query,
      },
    });
    if (error) {
      console.error("Error fetching games stats:", error);
      throw error;
    }
    return data;
  }

  ////////////////// ACTIVITIES //////////////////

  static async getActivity(id: number) {
    const { data, error } = await this.getClient().GET("/api/activity/{id}", {
      params: { path: { id } },
    });
    if (error) {
      console.error("Error fetching activity:", error);
      throw error;
    }
    return data;
  }

  static async getActivities(
    query: paths["/api/activities"]["get"]["parameters"]["query"],
  ) {
    const { data, error } = await this.getClient().GET("/api/activities", {
      params: {
        query,
      },
    });
    if (error) {
      console.error("Error fetching activities:", error);
      throw error;
    }
    return data;
  }

  static async getNewestActivity(
    query: paths["/api/activity/newest"]["get"]["parameters"]["query"],
  ) {
    const { data, error } = await this.getClient().GET("/api/activity/newest", {
      params: {
        query,
      },
    });
    if (error) {
      console.error("Error fetching newest activity:", error);
      throw error;
    }
    return data;
  }

  static async getOldestActivity(
    query: paths["/api/activity/oldest"]["get"]["parameters"]["query"],
  ) {
    const { data, error } = await this.getClient().GET("/api/activity/oldest", {
      params: {
        query,
      },
    });
    if (error) {
      console.error("Error fetching oldest activity:", error);
      throw error;
    }
    return data;
  }

  static async getTotals(
    query?: paths["/api/total"]["get"]["parameters"]["query"],
  ) {
    const { data, error } = await this.getClient().GET("/api/total", {
      params: {
        query,
      },
    });
    if (error) {
      console.error("Error fetching total:", error);
      throw error;
    }
    return data;
  }

  /////////////// IGDB /////////////////
  /** Returns URL to cover from IGDB */
  static async getIGDBGameInfo(
    igdb_id: number,
  ): Promise<
    paths["/api/igdb/game/{igdb_game_id}"]["get"]["responses"]["200"]["content"]["application/json"]
  > {
    const { data, error } = await this.getClient().GET(
      "/api/igdb/game/{igdb_game_id}",
      {
        params: {
          path: {
            igdb_game_id: igdb_id,
          },
        },
      },
    );
    if (error) {
      console.error("Error fetching IGDB game info:", error);
      throw error;
    }
    return data;
  }

  /////////////// SGDB /////////////////

  static async getBestSGDBGridForGame(
    sgdb_game_id: number,
  ): Promise<
    paths["/api/sgdb/{sgdb_game_id}/grids/best"]["get"]["responses"]["200"]["content"]["application/json"]
  > {
    const key = `api_getBestSGDBGridForGame_${sgdb_game_id}`;
    const cached = getSessionCache(key);
    if (cached) {
      return cached;
    }
    const { data, error } = await this.getClient().GET(
      "/api/sgdb/{sgdb_game_id}/grids/best",
      {
        params: {
          path: {
            sgdb_game_id,
          },
        },
      },
    );
    if (error) {
      console.error("Error fetching best grid:", error);
      throw error;
    }
    storeSessionCache(key, data);
    return data;
  }

  /*  static async searchSGDB(query: string) {
    const { data, error } = await this.getClient().GET("/api/sgdb/search", {
      params: {
        query: {
          query,
        },
      },
    });
    if (error) {
      console.error("Error searching SGDB:", error);
      throw error;
    }
    return data;
  } */

  static async getGrid(
    sgdb_game_id: number,
    grid_id: number,
  ): Promise<
    paths["/api/sgdb/{sgdb_game_id}/grids/{grid_id}"]["get"]["responses"]["200"]["content"]["application/json"]
  > {
    const key = `api_getGrid_${sgdb_game_id}_${grid_id}`;
    const cached = getSessionCache(key);
    if (cached) {
      return cached;
    }
    const { data, error } = await this.getClient().GET(
      "/api/sgdb/{sgdb_game_id}/grids/{grid_id}",
      {
        params: {
          path: {
            sgdb_game_id,
            grid_id,
          },
        },
      },
    );
    if (error) {
      console.error("Error fetching grid:", error);
      throw error;
    }
    storeSessionCache(key, data);
    return data;
  }

  ////////////////// CHART /////////////////////
  static async getChartsPlaytimeByDay(
    query: paths["/api/charts/playtime/by_day"]["get"]["parameters"]["query"],
  ) {
    const { data, error } = await this.getClient().GET(
      "/api/charts/playtime/by_day",
      {
        params: {
          query,
        },
      },
    );
    if (error) {
      console.error("Error fetching chart data:", error);
      throw error;
    }
    return data;
  }

  /////////////// DISCORD /////////////////
  static getDiscordAvatarUrl(discord_id: string) {
    return `/api/discord/${discord_id}/avatar`;
  }

  ////////////// MISC ///////////////
  static async ping() {
    const { data, error } = await this.getClient().GET("/api/ping");
    if (error) {
      console.error("Error pinging API:", error);
      throw error;
    }
    return data;
  }

  static async info() {
    const { data, error } = await this.getClient().GET("/api/info");
    if (error) {
      console.error("Error fetching API info:", error);
      throw error;
    }
    return data;
  }
}
