import createClient from "openapi-fetch";
import type { paths } from "./api.schema.d.ts"; // generated by openapi-typescript

// leave baseUrl empty to automatically append to the current origin
const client = createClient<paths>({
  // fetch: _fetch, // can hijack fetch if needed 🤔
  // baseUrl: "http://localhost:8000",
});

export class TimeplayedAPI {
  static getClient() {
    return client;
  }

  static async getUser(userId: string) {
    const { data, error } = await this.getClient().GET("/api/user/{userId}", {
      params: {
        path: {
          userId,
        },
      },
    });
    if (error) {
      console.error("Error fetching user:", error);
      throw error;
    }
    return data;
  }

  static async getActivity(activityId: number) {
    const { data, error } = await this.getClient().GET(
      "/api/activity/{activity_id}",
      {
        params: { path: { activity_id: activityId } },
      },
    );
    if (error) {
      console.error("Error fetching activity:", error);
      throw error;
    }
    return data;
  }

  static async getPlatform(platformId: number) {
    const { data, error } = await this.getClient().GET(
      "/api/platform/{platformId}",
      {
        params: {
          path: {
            platformId,
          },
        },
      },
    );
    if (error) {
      console.error("Error fetching platform:", error);
      throw error;
    }
    return data;
  }

  static async getGame(gameId: number) {
    const { data, error } = await this.getClient().GET("/api/game/{gameId}", {
      params: {
        path: {
          gameId,
        },
      },
    });
    if (error) {
      console.error("Error fetching game:", error);
      throw error;
    }
    return data;
  }

  static async getActivities(
    queryParams: paths["/api/activities"]["get"]["parameters"]["query"],
  ) {
    const { data, error } = await this.getClient().GET("/api/activities", {
      params: {
        query: queryParams,
      },
    });
    if (error) {
      console.error("Error fetching activities:", error);
      throw error;
    }
    return data;
  }

  static async getNewestActivity(
    queryParams: paths["/api/activity/newest"]["get"]["parameters"]["query"],
  ) {
    const { data, error } = await this.getClient().GET("/api/activity/newest", {
      params: {
        query: queryParams,
      },
    });
    if (error) {
      console.error("Error fetching newest activity:", error);
      throw error;
    }
    return data;
  }

  static async getOldestActivity(
    queryParams: paths["/api/activity/oldest"]["get"]["parameters"]["query"],
  ) {
    const { data, error } = await this.getClient().GET("/api/activity/oldest", {
      params: {
        query: queryParams,
      },
    });
    if (error) {
      console.error("Error fetching oldest activity:", error);
      throw error;
    }
    return data;
  }

  static async getUsers(
    queryParams: paths["/api/users"]["get"]["parameters"]["query"],
  ) {
    const { data, error } = await this.getClient().GET("/api/users", {
      params: {
        query: queryParams,
      },
    });
    if (error) {
      console.error("Error fetching users:", error);
      throw error;
    }
    return data;
  }

  static async getGames(
    queryParams: paths["/api/games"]["get"]["parameters"]["query"],
  ) {
    const { data, error } = await this.getClient().GET("/api/games", {
      params: {
        query: queryParams,
      },
    });
    if (error) {
      console.error("Error fetching games:", error);
      throw error;
    }
    return data;
  }

  static async getPlatforms(
    queryParams: paths["/api/platforms"]["get"]["parameters"]["query"],
  ) {
    const { data, error } = await this.getClient().GET("/api/platforms", {
      params: {
        query: queryParams,
      },
    });
    if (error) {
      console.error("Error fetching platforms:", error);
      throw error;
    }
    return data;
  }

  static async getTotals(
    queryParams?: paths["/api/totals"]["get"]["parameters"]["query"],
  ) {
    const { data, error } = await this.getClient().GET("/api/totals", {
      params: {
        query: queryParams,
      },
    });
    if (error) {
      console.error("Error fetching totals:", error);
      throw error;
    }
    return data;
  }

  static async getBestSGDBGridForGame(sgdb_game_id: number) {
    const { data, error } = await this.getClient().GET(
      "/api/sgdb/grids/{sgdb_game_id}/best",
      {
        params: {
          path: {
            sgdb_game_id,
          },
        },
      },
    );
    if (error) {
      console.error("Error fetching best grid:", error);
      throw error;
    }
    return data;
  }

  static async searchSGDB(query: string) {
    const { data, error } = await this.getClient().GET("/api/sgdb/search", {
      params: {
        query: {
          query,
        },
      },
    });
    if (error) {
      console.error("Error searching SGDB:", error);
      throw error;
    }
    return data;
  }
}
