name: Test

on:
  push:
    branches:
      - master
  pull_request:
  release:
    types: [published]

jobs:
  check-version:
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Check package.json version matches release tag
        run: make check-version TAG=${{ github.event.release.tag_name }}

  test-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        working-directory: backend
        run: pip install -r requirements.txt

      - name: Check formatting (black)
        working-directory: backend
        run: make format-check

      - name: Run tests (pytest)
        working-directory: backend
        run: make test

  test-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Check formatting (prettier)
        working-directory: frontend
        run: npm run format-check

      - name: Test building # TODO proper tests!
        working-directory: frontend
        run: npm run build
